import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.4.120/pdf.min.js"></script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.9.359/pdf.min.js" />
      </head>
      <body className={inter.className}>
        <nav className="bg-gray-800 text-white p-4">
          <ul className="flex space-x-4">
            <li><Link href="/" className="hover:text-gray-300">Home</Link></li>
            <li><Link href="/accounts" className="hover:text-gray-300">Accounts</Link></li>
            <li><Link href="/ocr" className="hover:text-gray-300">OCR</Link></li>
            <li><Link href="/openai" className="hover:text-gray-300">OpenAI</Link></li>
            <li><Link href="/invoice-processor" className="hover:text-gray-300">GPTProcessor</Link></li>
            <li><Link href="/ocr-gpt" className="hover:text-gray-300">OCR&GPT</Link></li>
            <li><Link href="/prompt" className="hover:text-gray-300">Prompt</Link></li>
            <li><Link href="/invoices" className="hover:text-gray-300">Invoices</Link></li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  )
}
